name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for using eunomia-bpf! We appreciate your help and we’ll take care of this as soon as possible.'
        pr-message: 'Thanks for your contribution! You are to making eunomia-bpf even better.'
